name: soul_note
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  audioplayers: ^5.2.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  emailjs: ^4.0.0
  uuid: ^4.5.2
  perfect_freehand: ^2.5.1
  path_drawing: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icon/icon.png

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat.ttf

# âœ… THIS MUST BE OUTSIDE flutter:
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png